Feature/enchancements
distributed-lab/vue-template pull request #9
Opened 2024-02-08 20:55 UTC by lukachi

2024-02-26 12:08 UTC, lukachi commented
FIXME:

1. Too much prioritized component styles
2. something wrong with ctc in toasts, e. g. can't access to $t, or $route, so custom components can't be fully implemented in toast popup
3. Modal props warnings
4. Fields emit change & input events twice
5. UICollapse ain't work properly if we call it in fields

2024-03-04 08:59 UTC, napalmpapalam requested changes

2024-03-04 08:59 UTC, napalmpapalam commented on .env-analyze
> +VITE_APP_NAME='React Template'
Vue Template

2024-03-04 08:59 UTC, napalmpapalam commented on .prettierrc
> +}
Half of the options have default values

```suggestion
{
  "semi": false,
  "singleQuote": true,
  "arrowParens": "avoid",
  "endOfLine": "auto",
  "printWidth": 100,
  "jsxSingleQuote": true,
}
```

2024-03-04 08:59 UTC, napalmpapalam commented on src/ui/UiCheckbox.vue
> +)
extract tuples into the constants

2024-04-06 10:33 UTC, merged